// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO members (group_id, email, phone, name, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, phone, name, group_id, user_id, created_at, updated_at, deleted_at
`

type CreateGroupMemberParams struct {
	GroupID int64       `json:"group_id"`
	Email   pgtype.Text `json:"email"`
	Phone   string      `json:"phone"`
	Name    string      `json:"name"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.GroupID,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.UserID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.GroupID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
