// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int64            `json:"id"`
	Title       pgtype.Text      `json:"title"`
	Image       pgtype.Text      `json:"image"`
	Description pgtype.Text      `json:"description"`
	GroupID     int64            `json:"group_id"`
	Status      pgtype.Text      `json:"status"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	Amount      pgtype.Int8      `json:"amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Group struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	UserID      pgtype.UUID      `json:"user_id"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type GroupAdmin struct {
	ID        int64            `json:"id"`
	GroupID   int64            `json:"group_id"`
	MemberID  int64            `json:"member_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Member struct {
	ID        int64            `json:"id"`
	Email     pgtype.Text      `json:"email"`
	Phone     string           `json:"phone"`
	Name      string           `json:"name"`
	GroupID   int64            `json:"group_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Rsvp struct {
	ID                 int64            `json:"id"`
	MemberID           int64            `json:"member_id"`
	EventID            int64            `json:"event_id"`
	HasPaid            pgtype.Bool      `json:"has_paid"`
	PaymentData        []byte           `json:"payment_data"`
	PaymentReferenceID pgtype.Int8      `json:"payment_reference_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
}
