// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupAdmin(ctx context.Context, arg CreateGroupAdminParams) (GroupAdmin, error)
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (Member, error)
	GetUserGrops(ctx context.Context, arg GetUserGropsParams) ([]Group, error)
	IsGroupAdmin(ctx context.Context, arg IsGroupAdminParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
