name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Change to your main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west2
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Build the Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/meet-loop-api .
          docker push gcr.io/$PROJECT_ID/meet-loop-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy meet-loop-api \
            --image gcr.io/$PROJECT_ID/meet-loop-api \
            --platform managed \
            --region <REGION>  # Replace with your desired region
